site_name: Grout
docs_dir: docs
site_url: https://grout.romm.app/
site_author: RomM Team
site_description: A RomM client for muOS, Knulli, ROCKNIX, Spruce and NextUI
repo_url: https://github.com/rommapp/grout
repo_name: rommapp/grout
edit_uri: edit/main/docs/

theme:
  name: material
  logo: resources/img/isotipo.png
  favicon: resources/img/isotipo.png
  features:
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    - toc.integrate
  language: en
  palette:
    scheme: slate
    primary: custom
    accent: custom
  custom_dir: overrides

plugins:
  - search
  - glightbox:
      skip_classes:
        - skip-lightbox

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - md_in_html
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Quick Start:
      - getting-started/index.md
      - muOS: getting-started/install-muos.md
      - Knulli: getting-started/install-knulli.md
      - ROCKNIX: getting-started/install-rocknix.md
      - Spruce: getting-started/install-spruce.md
      - NextUI: getting-started/install-nextui.md
  - User Guide:
      - Overview: guide/user-guide.md
      - Settings: guide/settings.md
      - Save Sync: guide/save-sync.md
  - Platforms:
      - muOS: platforms/muos.md
      - Knulli: platforms/knulli.md
      - ROCKNIX: platforms/rocknix.md
      - Spruce: platforms/spruce.md
      - NextUI: platforms/nextui.md
      - TrimUI: platforms/trimui.md
  - Development & Contributing:
      - Development Guide: development/development.md
      - Contributing Guide: development/contributing.md
      - State Machine: development/state-machine.md
      - Kudos: development/kudos.md

copyright: Copyright &copy; 2025 RomM Team

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rommapp/grout
      name: rommapp/grout
    - icon: fontawesome/brands/discord
      link: https://discord.gg/P5HtHnhUDH
      name: RomM Discord

extra_css:
  - resources/css/theme.css

watch:
  - docs
  - mkdocs.yml
  - overrides
